# Generated by Django 2.1.4 on 2019-01-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=250)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplectElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=60)),
                ('element_property', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=60)),
                ('inventory_id', models.CharField(max_length=10)),
                ('instrument_type', models.CharField(max_length=25)),
                ('complect_type', models.CharField(max_length=15)),
                ('complect_count', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=30)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicband.Instrument')),
            ],
        ),
        migrations.AddField(
            model_name='complectelement',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicband.Instrument'),
        ),
        migrations.AddField(
            model_name='comments',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicband.Instrument'),
        ),
    ]
