# Generated by Django 2.1.4 on 2019-01-01 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicband', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_status', models.CharField(max_length=20)),
                ('problem_pub_date', models.DateField(default=django.utils.timezone.now)),
                ('problem_name', models.TextField(max_length=250)),
                ('problem_planed_decisions', models.TextField(max_length=250)),
                ('problem_planed_cost_min', models.SmallIntegerField()),
                ('problem_planed_cost_max', models.SmallIntegerField()),
                ('priority', models.SmallIntegerField(max_length=3)),
                ('decision_deadline', models.DateField()),
                ('problem_final_cost', models.SmallIntegerField()),
                ('problem_final_decision', models.TextField(max_length=250)),
                ('problem_closer', models.CharField(max_length=80)),
                ('problem_close_date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ComplectElement',
            new_name='KitElement',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='complect_count',
            new_name='kit_count',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='complect_type',
            new_name='kit_type',
        ),
        migrations.AlterField(
            model_name='comments',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
