# Generated by Django 2.1.4 on 2019-01-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicband', '0002_auto_20190101_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='responsible',
            field=models.CharField(default='Admin', max_length=60),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='problems',
            name='priority',
            field=models.SmallIntegerField(),
        ),
    ]
