# Generated by Django 2.1.4 on 2019-01-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicband', '0004_auto_20190102_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='instrument',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='musicband.Instrument'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='kit_element',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='musicband.KitElement'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='instrument',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='musicband.Instrument'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='kit_element',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='musicband.KitElement'),
        ),
    ]
