# Generated by Django 2.1.4 on 2019-01-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicband', '0005_auto_20190102_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='responsible',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
