# Generated by Django 2.1.4 on 2019-01-02 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicband', '0006_auto_20190102_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_property',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='instrument',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
