# Generated by Django 2.1.4 on 2019-01-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicband', '0007_auto_20190102_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='inventory_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='kit_count',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='kit_type',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
