# Generated by Django 2.1.4 on 2019-01-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicband', '0008_auto_20190110_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_property',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='inventory_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='kit_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='kit_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='responsible',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
